#!/bin/bash

export PYTHONHOME=/Applications/QGIS-STAGING.app/Contents/Frameworks/Python.framework/Versions/Current
export PYTHONPATH=/Applications/QGIS-STAGING.app/Contents/Resources/python

/Applications/QGIS-STAGING.app/Contents/Frameworks/Python.framework/Versions/Current/bin/python3
